[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
ffi = true
# in foundry you can run bash scripts or other types of scripts but you need to have ffi = true in your foundry.toml
# HOWEVER, setting ffi = true allows foundry to run commands directly on your machine!!!
# so try to keep it off as long as possible
# See more config options https://github.com/foundry-rs/foundry/tree/master/config